# -*- coding: utf-8 -*-
"""Proyecto_Big

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNRf10YYBZKf5-AaFz1YQVQnj90IfPUH
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import pandas as pd

sales = pd.read_csv("sales_clean.csv")
specs = pd.read_csv("specs_clean.csv")

print(sales.shape)
print(specs.shape)

sales["merge_key"] = sales["brand_norm"].fillna("") + "_" + sales["model_norm"].fillna("")
specs["merge_key"] = specs["brand_norm"].fillna("") + "_" + specs["model_norm"].fillna("")

dataset_final = sales.merge(
    specs[[
        "merge_key",
        "name",
        "ram_gb",
        "storage_gb",
        "battery_mah",
        "main_camera_mp",
        "price_eur",
        "platform_os"
    ]],
    on="merge_key",
    how="left"
)

print("dataset_final:", dataset_final.shape)
display(dataset_final.head(10))

matches = dataset_final["name"].notna().sum()
total = len(dataset_final)
match_rate = matches / total * 100

print(f"Coincidencias: {matches} de {total}")
print(f"Porcentaje de match: {match_rate:.2f}%")

no_match = dataset_final[dataset_final["name"].isna()][
    ["brand", "mobile_model", "brand_norm", "model_norm"]
].drop_duplicates()

print("Modelos sin match:", len(no_match))
display(no_match)

import pandas as pd

# 1) Cargar los archivos limpios
sales = pd.read_csv("sales_clean.csv")
specs = pd.read_csv("specs_clean.csv")

# 2) Correcciones puntuales en ventas para mejorar el match
# Nota: Galaxy Note 20 se deja igual porque no aparece en specs_clean
sales.loc[
    (sales["brand_norm"] == "vivo") & (sales["model_norm"] == "y51"),
    "model_norm"
] = "y51 2020 september"

sales.loc[
    (sales["brand_norm"] == "samsung") & (sales["model_norm"] == "galaxy a51"),
    "model_norm"
] = "galaxy a51 5g"

sales.loc[
    (sales["brand_norm"] == "samsung") & (sales["model_norm"] == "galaxy s21"),
    "model_norm"
] = "galaxy s21 5g"

# 3) Crear llave de unión
sales["merge_key"] = sales["brand_norm"].fillna("") + "_" + sales["model_norm"].fillna("")
specs["merge_key"] = specs["brand_norm"].fillna("") + "_" + specs["model_norm"].fillna("")

# 4) Hacer el merge
dataset_final = sales.merge(
    specs[
        [
            "merge_key",
            "name",
            "ram_gb",
            "storage_gb",
            "battery_mah",
            "main_camera_mp",
            "price_eur",
            "platform_os"
        ]
    ],
    on="merge_key",
    how="left"
)

# 5) Revisar resultado
matches = dataset_final["name"].notna().sum()
total = len(dataset_final)
match_rate = matches / total * 100

print(f"Coincidencias: {matches} de {total}")
print(f"Porcentaje de match: {match_rate:.2f}%")

print("\nModelos que siguen sin match:")
display(
    dataset_final[dataset_final["name"].isna()][
        ["brand", "mobile_model", "brand_norm", "model_norm"]
    ].drop_duplicates()
)

# 6) Guardar nuevo archivo
dataset_final.to_csv("dataset_final_merged_v2.csv", index=False)
print("\nArchivo creado: dataset_final_merged_v2.csv")

from google.colab import files
files.download("dataset_final_merged_v2.csv")

dataset_final.to_csv("dataset_final_merged.csv", index=False)
print("Archivo creado: dataset_final_merged.csv")

from google.colab import files
files.download("dataset_final_merged.csv")

"""#Proceso de analisis con el dataset

### Subir el archivo final
"""

from google.colab import files
uploaded = files.upload()

"""### Importar librerías"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""### Leer el dataset"""

df = pd.read_csv("dataset_final_merged_v2.csv")
print(df.shape)
df.head()

"""### Revisar estructura"""

print("Columnas:")
print(df.columns.tolist())

print("\nTipos de datos:")
print(df.dtypes)

print("\nNulos por columna:")
print(df.isnull().sum().sort_values(ascending=False))

"""### Estandarizar columnas clave"""

df["units_sold"] = pd.to_numeric(df["units_sold"], errors="coerce")
df["price_per_unit"] = pd.to_numeric(df["price_per_unit"], errors="coerce")
df["total_revenue"] = pd.to_numeric(df["total_revenue"], errors="coerce")
df["customer_age"] = pd.to_numeric(df["customer_age"], errors="coerce")
df["customer_ratings"] = pd.to_numeric(df["customer_ratings"], errors="coerce")
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["ram_gb"] = pd.to_numeric(df["ram_gb"], errors="coerce")
df["storage_gb"] = pd.to_numeric(df["storage_gb"], errors="coerce")
df["battery_mah"] = pd.to_numeric(df["battery_mah"], errors="coerce")
df["main_camera_mp"] = pd.to_numeric(df["main_camera_mp"], errors="coerce")
df["price_eur"] = pd.to_numeric(df["price_eur"], errors="coerce")

df["date"] = pd.to_datetime(df["date"], errors="coerce")

print(df.dtypes)

"""### Crear dataset procesado"""

df_processed = df.copy()

df_processed["brand"] = df_processed["brand"].astype(str).str.strip()
df_processed["mobile_model"] = df_processed["mobile_model"].astype(str).str.strip()
df_processed["city"] = df_processed["city"].astype(str).str.strip()
df_processed["payment_method"] = df_processed["payment_method"].astype(str).str.strip()

# Variables derivadas
df_processed["revenue_per_unit_sold"] = df_processed["total_revenue"] / df_processed["units_sold"]
df_processed["has_specs"] = np.where(df_processed["name"].notna(), 1, 0)

print(df_processed.shape)
df_processed.head()

"""### Guardar versión procesada"""

df_processed.to_csv("dataset_processed_colab.csv", index=False)
print("Archivo creado: dataset_processed_colab.csv")

"""# Ahora empezamos con el analisi

### Resumen general
"""

print("Total registros:", len(df_processed))
print("Total unidades vendidas:", df_processed["units_sold"].sum())
print("Ingreso total:", df_processed["total_revenue"].sum())
print("Marcas únicas:", df_processed["brand"].nunique())
print("Modelos únicos:", df_processed["mobile_model"].nunique())
print("Ciudades únicas:", df_processed["city"].nunique())

"""### Ventas por marca"""

brand_sales = df_processed.groupby("brand", as_index=False).agg(
    total_units=("units_sold", "sum"),
    total_revenue=("total_revenue", "sum")
).sort_values("total_units", ascending=False)

brand_sales.head(10)

"""### Gráfica de unidades vendidas por marca"""

top_brands = brand_sales.head(10)

plt.figure(figsize=(10,6))
plt.bar(top_brands["brand"], top_brands["total_units"])
plt.title("Top 10 marcas por unidades vendidas")
plt.xlabel("Marca")
plt.ylabel("Unidades vendidas")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Ingresos por marca"""

top_brands_revenue = brand_sales.sort_values("total_revenue", ascending=False).head(10)

plt.figure(figsize=(10,6))
plt.bar(top_brands_revenue["brand"], top_brands_revenue["total_revenue"])
plt.title("Top 10 marcas por ingresos")
plt.xlabel("Marca")
plt.ylabel("Ingresos totales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Modelos más vendidos"""

top_models = df_processed.groupby(["brand", "mobile_model"], as_index=False).agg(
    total_units=("units_sold", "sum"),
    total_revenue=("total_revenue", "sum")
).sort_values("total_units", ascending=False)

top_models.head(10)

"""### Ventas por ciudad"""

city_sales = df_processed.groupby("city", as_index=False).agg(
    total_units=("units_sold", "sum"),
    total_revenue=("total_revenue", "sum")
).sort_values("total_units", ascending=False)

city_sales.head(10)

"""### Ventas por año"""

year_sales = df_processed.groupby("year", as_index=False).agg(
    total_units=("units_sold", "sum"),
    total_revenue=("total_revenue", "sum")
).sort_values("year")

year_sales

plt.figure(figsize=(8,5))
plt.plot(year_sales["year"], year_sales["total_units"], marker="o")
plt.title("Evolución de unidades vendidas por año")
plt.xlabel("Año")
plt.ylabel("Unidades vendidas")
plt.tight_layout()
plt.show()

"""### Relación entre precio y ventas"""

df_price = df_processed.dropna(subset=["price_per_unit", "units_sold"])

plt.figure(figsize=(8,5))
plt.scatter(df_price["price_per_unit"], df_price["units_sold"])
plt.title("Relación entre precio por unidad y unidades vendidas")
plt.xlabel("Precio por unidad")
plt.ylabel("Unidades vendidas")
plt.tight_layout()
plt.show()

"""### Relación entre batería y ventas"""

df_battery = df_processed.dropna(subset=["battery_mah", "units_sold"])

plt.figure(figsize=(8,5))
plt.scatter(df_battery["battery_mah"], df_battery["units_sold"])
plt.title("Relación entre batería y unidades vendidas")
plt.xlabel("Batería (mAh)")
plt.ylabel("Unidades vendidas")
plt.tight_layout()
plt.show()

"""### Relación entre RAM y ventas"""

df_ram = df_processed.dropna(subset=["ram_gb", "units_sold"])

plt.figure(figsize=(8,5))
plt.scatter(df_ram["ram_gb"], df_ram["units_sold"])
plt.title("Relación entre RAM y unidades vendidas")
plt.xlabel("RAM (GB)")
plt.ylabel("Unidades vendidas")
plt.tight_layout()
plt.show()

"""### Correlación numérica"""

corr_cols = [
    "units_sold",
    "price_per_unit",
    "total_revenue",
    "customer_age",
    "customer_ratings",
    "ram_gb",
    "storage_gb",
    "battery_mah",
    "main_camera_mp"
]

correlation = df_processed[corr_cols].corr()
correlation

"""### Descargar archivo procesado"""

from google.colab import files
files.download("dataset_processed_colab.csv")

"""Ingesta / gestión

carga del archivo

validación de estructura

transformación

tipificación

generación de dataset procesado

Análisis

KPIs generales

análisis por marca

análisis por modelo

análisis por ciudad

análisis temporal

relación entre variables técnicas y ventas
"""

